name: cleanpython
channels:
  - astropy
  - defaults
dependencies:
  - pip=19.2.3
  - pytest==5.2.0
  - pytest-cov==2.7.1
  - pip:
    - astroquery~=0.4.2.dev6366
    - astropy==4.0.1.post1
    - toml~=0.10.1
    - requests~=2.24.0
    - pandas~=1.1.1
    - matplotlib~=3.3.1

