"""
@author: Maria H. Sarmiento Carrión
@contact: mhsarmiento@sciops.esa.int
European Space Astronomy Centre (ESAC)
European Space Agency (ESA)
Created on 29 Sep. 2020
"""

E2E_REPORT_TITLE = "Results of GAIA E2E test for Astroquery"

# Test constants
TEST_NUMBER_ERROR = "Test does not exit"

# TEST report filename pattern
REPORT_FILE_NAME_PATTERN = "E2ETestResults_@TEST_NAME@.toml"
TEST_NAME_PATTERN = "@TEST_NAME@"
TABLE_NAME_PATTERN = "@TABLE_NAME@"
SCHEMA_PATTERN = "@SCHEMA_NAME@"
QUERY_PATTERN = "@QUERY_PATTERN@"
JOB_ID_PATTERN = "@JOB_ID@"
FULL_QUALIFIED_USER_TABLE_NAME_PATTERN = "user_@LOGIN_USER@.@TABLE_NAME@"
USER_SCHEMA_PATTERN = "user_@LOGIN_USER@"
FULL_QUALIFIED_TABLE_NAME_PATTERN = "@SCHEMA_NAME@.@TABLE_NAME@"
FULL_QUALIFIED_PATTERN = "@FULL_QUALIFIED_PATTERN@"
LOGIN_USER_PATTERN = "@LOGIN_USER@"
FULL_QUALIFIED_TABLE_NAME_JOB_ID_PATTERN = 'user_@LOGIN_USER@.@JOB_ID@'
RETRIEVAL_TYPE_PATTERN = "@RETRIEVAL_TYPE@"

# Environment Names
ENV_LOCAL = "LOCAL"
ENV_DEV = "DEV"
ENV_PRE = "PRE"
ENV_VAL = "VAL"
ENV_OPE = "OPE"

# Test Names
TEST_LOGIN = 'LOGIN'
TEST_LOGOUT = 'LOGOUT'
TEST_QUERY_OBJECT = 'QUERY_OBJECT'
TEST_CONE_SEARCH = 'CONE_SEARCH'
TEST_GET_PUBLIC_TABLES = 'GET_PUBLIC_TABLES'
TEST_LOAD_TABLE = 'LOAD_TABLE'
TEST_SYNCHRONOUS_QUERY = 'SYNCHRONOUS_QUERY'
TEST_SYNCHRONOUS_ON_THE_FLY_QUERY = 'SYNCHRONOUS_ON_THE_FLY_QUERY'
TEST_ASYNCHRONOUS_QUERY = 'ASYNCHRONOUS_QUERY'
TEST_LIST_SHARED_TABLES = 'LIST_SHARED_TABLES'
TEST_DELETE_TABLE = 'DELETE_TABLE'
TEST_UPLOAD_TABLE_FROM_URL = 'UPLOAD_TABLE_FROM_URL'
TEST_UPLOAD_TABLE_FROM_FILE = 'UPLOAD_TABLE_FROM_FILE'
TEST_UPLOAD_TABLE_FROM_JOB = 'UPLOAD_TABLE_FROM_JOB'
TEST_UPLOAD_TABLE_FROM_ASTROPY_TABLE = 'UPLOAD_TABLE_FROM_ASTROPY_TABLE'
TEST_CROSS_MATCH = 'CROSS_MATCH'
TEST_DATALINK = 'DATALINK'
TEST_DATALINK_COMPARE = 'DATALINK_COMPARE'

# Dictionary with the #idNumber of the test plus its key_word
TEST_SET = {
    '#1': TEST_LOGIN,
    '#2': TEST_LOGOUT,
    '#3': TEST_QUERY_OBJECT,
    '#4': TEST_CONE_SEARCH,
    '#5': TEST_GET_PUBLIC_TABLES,
    '#6': TEST_LOAD_TABLE,
    '#7': TEST_SYNCHRONOUS_QUERY,
    '#8': TEST_SYNCHRONOUS_ON_THE_FLY_QUERY,
    '#9': TEST_ASYNCHRONOUS_QUERY,
    '#10': TEST_LIST_SHARED_TABLES,
    '#11': TEST_DELETE_TABLE,
    '#12': TEST_UPLOAD_TABLE_FROM_URL,
    '#13': TEST_UPLOAD_TABLE_FROM_FILE,
    '#14': TEST_UPLOAD_TABLE_FROM_JOB,
    '#15': TEST_UPLOAD_TABLE_FROM_ASTROPY_TABLE,
    '#16': TEST_CROSS_MATCH,
    '#17': TEST_DATALINK,
    '#26': TEST_DATALINK_COMPARE
}

BASIC_TEMPLATE = {
    'test_description': 'N/A',
    'request_sent': 'N/A',
    'test_additional_info': 'N/A',
    'test_result': 'NOT PASSED',
    'test_started': 'yyyy-mm-dd hh:mm:ss',
    'test_finished': 'yyyy-mm-dd hh:mm:ss'
}
